#!/bin/bash

#text,A=Merah,B=Hijau,C=Magenta,D=Cyan
A='\033[1;31m'
B='\033[1;32m'
C='\033[1;35m'
D='\033[1;36m'
E='\033[1;30m'
#background,A1=Merah,B1=Hijau,C1=Magenta,D1=Cyan
A1='\033[1;41m'
B1='\033[1;42m'
C1='\033[1;45m'
D1='\033[1;46m'
#reset
R='\033[0m'

echo -e "${D}————————————————————————————————————————————————————————————————${R}"
echo -e "${D1}                   ${E}Senarai Servis & Protokol${R}                    ${R}"
echo -e "${D}————————————————————————————————————————————————————————————————${R}"
