#!/bin/bash

#text,A=Merah,B=Hijau,C=Magenta,D=Cyan
A='\033[1;31m'
B='\033[1;32m'
C='\033[1;35m'
D='\033[1;36m'
#background,A1=Merah,B1=Hijau,C1=Magenta,D1=Cyan
A1='\033[1;41m'
B1='\033[1;42m'
C1='\033[1;45m'
D1='\033[1;46m'
#reset
R='\033[0m'

echo -e "${D}——————————————————————————————————————————————————————————${R}"
echo -e "${D1}                         Menu Xray                        ${R}"
echo -e "${D}——————————————————————————————————————————————————————————${R}"c
echo -e "Xray Xtls"
echo -e "${B}[01]${R} ► Membuat akaun Xray Xtls"
echo -e "${B}[02]${R} ► Memadam akaun Xray Xtls"
echo -e "${B}[03]${R} ► Menambah masa aktif akaun Xray Xtls"
echo -e "${B}[04]${R} ► Cek user login akaun Xray Xtls"
echo -e ""
echo -e "${D}——————————————————————————————————————————————————————————${R}"
echo -e "Xray Vless"
