#!/bin/bash

cd /usr/bin

rm add-xrayxtls
rm port-xraygrpc
rm cek-xrayxtls
rm renew-xrayxtls
rm clearlog

wget -O add-xrayxtls "https://raw.githubusercontent.com/rewasu91/server/main/add/add-xrayxtls.sh"
wget -O port-xraygrpc "https://raw.githubusercontent.com/rewasu91/server/main/editport/port-xraygrpc.sh"
wget -O cek-xrayxtls "https://raw.githubusercontent.com/rewasu91/server/main/cek/cek-xrayxtls.sh"
wget -O renew-xrayxtls "https://raw.githubusercontent.com/rewasu91/server/main/renew/renew-xrayxtls.sh"
wget -O clearlog "https://raw.githubusercontent.com/rewasu91/server/main/mix/clearlog.sh"

chmod +x add-xrayxtls
chmod +x port-xraygrpc
chmod +x cek-xrayxtls
chmod +x renew-xrayxtls
chmod +x clearlog
